// Generated by CoffeeScript 1.4.0
(function() {
  var float, integer, kernel, mykernel, _ref;

  _ref = require('./cello'), kernel = _ref.kernel, integer = _ref.integer, float = _ref.float;

  kernel(mykernel = function(globals, shared, locals) {
    var a;
    return integer(a = globals.a);
  });

}).call(this);
