// Generated by CoffeeScript 1.4.0
(function() {
  var C, compile, run, src, _ref;

  _ref = require('cello'), C = _ref.C, compile = _ref.compile, run = _ref.run;

  src = C({
    indent: "  ",
    debug: false
  })(function() {
    var main, x;
    include('stdio.h');
    include('stdlib.h');
    int(x = 40);
    return main = function() {
      var y;
      int(y = 43 + x);
      return printf("hello");
    };
  });

  console.log("source:\n" + src);

  run(src, function(output) {
    return console.log("output: " + output);
  });

}).call(this);
