// Generated by CoffeeScript 1.4.0
(function() {
  var C, compile, options, run, src, _ref;

  _ref = require('cello'), C = _ref.C, compile = _ref.compile, run = _ref.run;

  require('colors');

  options = {
    indent: "  ",
    evaluate: function() {
      return [Math.random];
    },
    ignore: function() {
      return [];
    },
    debug: false
  };

  src = C(options)(function() {
    var main, x;
    include('stdio.h');
    include('stdlib.h');
    int(x = 40);
    return main = function() {
      var $p2, a, i, p1, seed, y;
      printf("hello, ");
      int(y = 43 + x / 10);
      printf("result is %i", y);
      int(a = [0, 0, 0, 1, 0]);
      int(b[5] = [0]);
      float(seed = Math.round(Math.random() * 1000));
      char(p1 = 127);
      char($p2 = malloc(sizeof(char)));
      int(i = 0);
      while (i < 10000) {
        ++i;
      }
      while (i > 10000) {
        i--;
      }
      return 0;
    };
  });

  console.log("" + src);

  run(src, function(err, output) {
    if (err) {
      throw new Error(err.red);
    } else {
      return console.log(("" + output).green);
    }
  });

}).call(this);
